### ISSUE TITLE
API Key in Coding

### ISSUE THREAD

**Issue by Cahllagerfeld** [elenajp/weatherApp#1]
In [this](https://github.com/elenajp/weatherApp/blob/161df90bb7e48b566d757a0dd73e18c95474694b/main.py#L17) line is a API-Token. In case thats a real, and not a dummy you shouldnt commit it and maybe generate a new one, as this key is public now :(

**Comment by Cahllagerfeld** [comment]
Unfortunately I'm not into python to open a PR for that..

**Comment by elenajp** [comment]
Thank you so much for pointing that out to me. This api key is no longer in use. Sorry for the late reply, I somehow missed the issue you raised but I appreciate it! Have an awesome day 😀
